### ISSUE TITLE
msh_ply__calculate_elem_size_binary doesn't handle elements with a mix of list and non-list properties

### ISSUE THREAD

**Issue by vilya** [mhalber/msh#1]
msh_ply__calculate_elem_size_binary seems to assume that every property in the element is a list property, if I'm understanding the code correctly. There are some models where this isn't the case and they fail to parse. Models like this are pretty uncommon, but I've found two of them so far:

1. The classic [armadillo model](http://graphics.stanford.edu/pub/3Dscanrep/armadillo/Armadillo.ply.gz) has an additional per-face `intensity` property.
2. The dragon model (`dragon/geometry/dragon_remeshed.ply`) from [pbrt-v3-scenes](https://pbrt.org/scenes-v3.html) has per-face normals.

Hope that's useful. Great work on msh_ply by the way!

**Comment by mhalber** [comment]
Hi Vilya!
Thanks so much for pointing this out - clearly this should be rectified. I will take look to see what needs to be done to ensure these models get parsed.
